#!/usr/bin/env bash

# First-time setup script for .zsh configuration
# This script installs all required dependencies for the zsh configuration

set -e  # Exit on error

ZSH_DIR="$HOME/.zsh"
INITIALIZED_FILE="$ZSH_DIR/.initialized"

echo "=========================================="
echo "  .zsh Configuration - First Time Setup  "
echo "=========================================="
echo ""

# Function to check if a command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Install Homebrew if not already installed
if ! command_exists brew; then
  echo "Installing Homebrew package manager..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Add Homebrew to PATH for Apple Silicon Macs
  if [[ $(uname -m) == "arm64" ]]; then
    echo "Configuring Homebrew PATH for Apple Silicon..."
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
else
  echo "Homebrew is already installed"
fi

# Update Homebrew
echo "Updating Homebrew..."
brew update

# Install Starship prompt
if ! command_exists starship; then
  echo "Installing Starship prompt..."
  brew install starship
else
  echo "Starship is already installed"
fi

# Install Neovim (required for NvChad)
if ! command_exists nvim; then
  echo "Installing Neovim..."
  brew install neovim
else
  echo "Neovim is already installed"
fi

# Install other useful tools
echo "Installing additional development tools..."
TOOLS=(
  "git"          # Version control
  "gh"           # GitHub CLI
  "fzf"          # Fuzzy finder
  "ripgrep"      # Better grep
  "fd"           # Better find
  "bat"          # Better cat
  "eza"          # Better ls (formerly exa)
  "zoxide"       # Better cd
)

for tool in "${TOOLS[@]}"; do
  if ! command_exists "$tool"; then
    echo "  Installing $tool..."
    brew install "$tool"
  else
    echo "  $tool is already installed"
  fi
done

# Install NvChad
NVCHAD_DIR="$HOME/.config/nvim"
if [ ! -d "$NVCHAD_DIR" ]; then
  echo "Installing NvChad configuration..."
  git clone https://github.com/NvChad/starter "$NVCHAD_DIR"
else
  echo "NvChad is already installed"
fi

# Initialize zgenom submodule if not already done
if [ ! -f "$ZSH_DIR/framework/zgenom/zgenom.zsh" ]; then
  echo "Initializing zgenom submodule..."
  cd "$ZSH_DIR"
  git submodule update --init --recursive --remote

  # Ensure submodule is on the main branch, not detached HEAD
  cd "$ZSH_DIR/framework/zgenom"
  git checkout main
  cd "$ZSH_DIR"
fi

echo ""
echo "=========================================="
echo "  Setup completed successfully           "
echo "=========================================="
echo ""
echo "Creating initialization marker..."

# Create the .initialized file
cat > "$INITIALIZED_FILE" << EOF
### NOTE: THIS FILE IS AUTO-GENERATED BY setup.sh FOR THE PURPOSE OF TRACKING
### FIRST-TIME SETUP COMPLETION. DO NOT EDIT OR DELETE THIS FILE MANUALLY.
###
### If you want to re-run the setup process, simply delete this file and
### restart your shell or source init.zsh again.
###
### Setup completed on: $(date)
EOF

echo ""
echo "Setup process finished. Please restart your shell or run: source ~/.zsh/init.zsh"
echo ""
